import {
  Home,
  Compass,
  ClipboardList,
  KanbanSquare,
  Layers,
  Zap,
  TriangleAlert,
  Bookmark,
  ChartColumn,
  Calculator,
  Presentation,
  Play,
  Calendar,
  Layers3,
  BookOpen,
  FileText,
  Type,
  Building2,
  Users,
  Award,
  Briefcase,
  Lightbulb,
  Pencil,
  Mail,
  GraduationCap,
  Rss,
  Boxes,
  MessageSquare,
  type LucideIcon,
} from "lucide-react";

/** Maps nav `icon` keys to lucide line-icons. */
export const iconRegistry: Record<string, LucideIcon> = {
  home: Home,
  compass: Compass,
  clipboard: ClipboardList,
  kanban: KanbanSquare,
  stack: Layers,
  bolt: Zap,
  alert: TriangleAlert,
  bookmark: Bookmark,
  chart: ChartColumn,
  calculator: Calculator,
  presentation: Presentation,
  play: Play,
  calendar: Calendar,
  cards: Layers3,
  book: BookOpen,
  doc: FileText,
  type: Type,
  building: Building2,
  users: Users,
  award: Award,
  briefcase: Briefcase,
  lightbulb: Lightbulb,
  pencil: Pencil,
  mail: Mail,
  grad: GraduationCap,
  feed: Rss,
  spaces: Boxes,
  chat: MessageSquare,
};
